### ISSUE TITLE
Enable Hive Metastore metrics

### ISSUE THREAD

**Issue by pradeepbhadani** [ExpediaInc/apiary-metastore-docker#4]
_As a SysOps_
_I want to enable Hive Metastore metrics_
_So that process health can be monitored_

**Acceptance Criteria:**
* Hive metastore emits metrics to a file

**Comment by pradeepbhadani** [comment]
Raised https://github.com/ExpediaInc/apiary-metastore-docker/pull/5

**Comment by mroark1m** [comment]
@pradeepbhadani to @rpoluri 's comment on the PR, how will you access the file on the docker instance? Should we add cloudwatch to the scope of this issue?

**Comment by pradeepbhadani** [comment]
@mroark1m - the ways its deployed in EC2 instance is - a python script reads this output file and send metrics to Graphite.
